name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by Event: ${{ github.event_name }}"
          echo "Reference Branch: ${{ github.ref }} ."
      - uses: actions/checkout@v3.5.2
      
      - name: List all files in repository
        run: |
          echo "Contents of {{ github.repository }} repo: "
          tree

    
